name = input("What is your name?: ")
favorite_food = input("What is your favorite food?: ")
favorite_music = input("What is your favorite music?: ")
location = input("Where do you live?: ")
print()
print()
print("You are ")
print(name)
print("You're probably hungry for ")
print(favorite_food)
print("and you're definitely getting your groove on to ")
print(favorite_music)
print("living in the amazing ")
print(location)